# -*- mode: ruby -*-
# vi: set ft=ruby :

# Options for the bootstrap script are passed in the BOOT_OPTS environment variable
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define :pr_centos7
  config.vm.provision :shell, :path => "../../bootstrap-unix.sh", :args => ENV["BOOT_OPTS"]
end
