# -*- mode: ruby -*-
# vi: set ft=ruby :

# Options for the bootstrap script are passed in the BOOT_OPTS environment variable
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define :pr_centos8
  config.vm.provision :shell, :path => "../../bootstrap-unix.sh", :args => ENV["BOOT_OPTS"]
  # At the time of this writing installing guest additions fails
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
  end
end
